import { Letter } from '@/lib/validators/game-state';

export const LETTERS: Record<string, Letter> = {
	A: { char: 'A', rarity: 5, score: 1 },
	B: { char: 'B', rarity: 2, score: 4 },
	C: { char: 'C', rarity: 3, score: 5 },
	D: { char: 'D', rarity: 4, score: 3 },
	E: { char: 'E', rarity: 5, score: 1 },
	F: { char: 'F', rarity: 2, score: 5 },
	G: { char: 'G', rarity: 3, score: 3 },
	H: { char: 'H', rarity: 3, score: 4 },
	I: { char: 'I', rarity: 5, score: 1 },
	J: { char: 'J', rarity: 1, score: 7 },
	K: { char: 'K', rarity: 2, score: 6 },
	L: { char: 'L', rarity: 4, score: 3 },
	M: { char: 'M', rarity: 3, score: 4 },
	N: { char: 'N', rarity: 5, score: 2 },
	O: { char: 'O', rarity: 5, score: 1 },
	P: { char: 'P', rarity: 3, score: 4 },
	Q: { char: 'Q', rarity: 1, score: 8 },
	R: { char: 'R', rarity: 4, score: 2 },
	S: { char: 'S', rarity: 5, score: 2 },
	T: { char: 'T', rarity: 5, score: 2 },
	U: { char: 'U', rarity: 4, score: 4 },
	V: { char: 'V', rarity: 2, score: 5 },
	W: { char: 'W', rarity: 2, score: 5 },
	X: { char: 'X', rarity: 1, score: 7 },
	Y: { char: 'Y', rarity: 2, score: 4 },
	Z: { char: 'Z', rarity: 1, score: 8 },
	'?': { char: '?', rarity: 0, score: 0 },
};
